mostly futzing with tmux

diff --git a/zsh/dotfiles/zshrc b/zsh/dotfiles/zshrc
--- a/zsh/dotfiles/zshrc
+++ b/zsh/dotfiles/zshrc
@@ -212,44 +212,45 @@ zstyle ':completion:*' word true
 
 ###############################
 ## make funny keys work right
-autoload zkbd
-function zkbd_file() {
-    [[ -f ~/.zkbd/${TERM}-${VENDOR}-${OSTYPE} ]] && printf '%s' ~/".zkbd/${TERM}-${VENDOR}-${OSTYPE}" && return 0
-    [[ -f ~/.zkbd/${TERM}-${DISPLAY}          ]] && printf '%s' ~/".zkbd/${TERM}-${DISPLAY}"          && return 0
-    return 1
-}
-
-keyfile=$(zkbd_file)
-ret=$?
-if [[ ${ret} -ne 0 ]]; then
-    zkbd
-    keyfile=$(zkbd_file)
-    ret=$?
-fi
-if [[ ${ret} -eq 0 ]] ; then
-    source "${keyfile}"
-else
-    printf 'Failed to setup keys using zkbd.\n'
-fi
-unfunction zkbd_file; unset keyfile ret
-source ~/.zkbd/$TERM-${DISPLAY:-$VENDOR-$OSTYPE}
-# setup key accordingly
-[[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line
-[[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line
-[[ -n "${key[Insert]}"  ]]  && bindkey  "${key[Insert]}"  overwrite-mode
-[[ -n "${key[Delete]}"  ]]  && bindkey  "${key[Delete]}"  delete-char
-[[ -n "${key[Up]}"      ]]  && bindkey  "${key[Up]}"      up-line-or-history
-[[ -n "${key[Down]}"    ]]  && bindkey  "${key[Down]}"    down-line-or-history
-[[ -n "${key[Left]}"    ]]  && bindkey  "${key[Left]}"    backward-char
-[[ -n "${key[Right]}"   ]]  && bindkey  "${key[Right]}"   forward-char
-
-
-# _tmux_pane_complete() {
-#   [[ -z "$TMUX_PANE" ]] && return 1
-#   local -a -U words
-#   words=(${=$(tmux capture-pane \; show-buffer \; delete-buffer)})
-#   compadd -a words
+# i don't think i like this anymore
+# autoload zkbd
+# function zkbd_file() {
+#     [[ -f ~/.zkbd/${TERM}-${VENDOR}-${OSTYPE} ]] && printf '%s' ~/".zkbd/${TERM}-${VENDOR}-${OSTYPE}" && return 0
+#     [[ -f ~/.zkbd/${TERM}-${DISPLAY}          ]] && printf '%s' ~/".zkbd/${TERM}-${DISPLAY}"          && return 0
+#     return 1
 # }
 
-# compdef -k _tmux_pane_complete menu-select '^T'
+# keyfile=$(zkbd_file)
+# ret=$?
+# if [[ ${ret} -ne 0 ]]; then
+#     zkbd
+#     keyfile=$(zkbd_file)
+#     ret=$?
+# fi
+# if [[ ${ret} -eq 0 ]] ; then
+#     source "${keyfile}"
+# else
+#     printf 'Failed to setup keys using zkbd.\n'
+# fi
+# unfunction zkbd_file; unset keyfile ret
+# source ~/.zkbd/$TERM-${DISPLAY:-$VENDOR-$OSTYPE}
+# # setup key accordingly
+# [[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line
+# [[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line
+# [[ -n "${key[Insert]}"  ]]  && bindkey  "${key[Insert]}"  overwrite-mode
+# [[ -n "${key[Delete]}"  ]]  && bindkey  "${key[Delete]}"  delete-char
+# [[ -n "${key[Up]}"      ]]  && bindkey  "${key[Up]}"      up-line-or-history
+# [[ -n "${key[Down]}"    ]]  && bindkey  "${key[Down]}"    down-line-or-history
+# [[ -n "${key[Left]}"    ]]  && bindkey  "${key[Left]}"    backward-char
+# [[ -n "${key[Right]}"   ]]  && bindkey  "${key[Right]}"   forward-char
+
+
+_tmux_pane_complete() {
+  [[ -z "$TMUX_PANE" ]] && return 1
+  local -a -U words
+  words=(${=$(tmux capture-pane \; show-buffer \; delete-buffer)})
+  compadd -a words
+}
+
+compdef -k _tmux_pane_complete menu-select '^T'
 
